your commit message
NCAR/micm pull request #100
Opened 2023-06-28 09:20 UTC by aharonYK

hello, I added the changes you wanted.
can you please give me your idea of it?
also, I added the build and installation according to the [tuv-x](https://github.com/NCAR/tuv-x) readme. md
hope you will like it
if there you want me to fix something I will be more than happy to do it.
thanks for the option to learn and work with you

2023-07-03 14:36 UTC, K20shores commented on README.md
> +./micm examples/full_config.json
MICM does not have an executable standalone tool. Please remove this line and the comment

2023-07-03 14:36 UTC, K20shores commented on README.md
> +You will now have a runnable exectubable for `mcim` and the tests in the build directory.
Again, no executable. Please remove this line and the command below

2023-07-03 14:39 UTC, K20shores requested changes

2023-07-03 14:39 UTC, K20shores commented on README.md
> +- [json-fortran](https://github.com/jacobwilliams/json-fortran)
```suggestion
- [json-fortran](https://github.com/jacobwilliams/json-fortran) This is only required for the regression tests.
```

2023-07-03 15:19 UTC, mattldawson requested changes
Looks good! Just a few suggested changes

2023-07-03 15:19 UTC, mattldawson commented on README.md
> +added to your system path to make the executable useable from any directory.
```suggestion
After completing the previous step run `sudo make install`.
This will install the MICM static library.
```

2023-07-03 15:19 UTC, mattldawson commented on README.md
> +`sudo make uninstall` from the build directory.
```suggestion
If you would later like to uninstall MICM, you can run
`sudo make uninstall` from the build directory.
```

2023-07-03 15:19 UTC, mattldawson commented on README.md
> +- [GPL 2.0](/LICENSE)
```suggestion
- [Apache 2.0](/LICENSE)
```

2023-07-13 16:51 UTC, K20shores commented
closes #95

2023-07-13 16:58 UTC, merged