Config parser
NCAR/micm pull request #255
Opened 2023-09-25 21:44 UTC by dwfncar

- Read CAMP files list from a top-level config file named config.json (should this be made a parameter to JsonReaderPolicy::Parse?).
- If config.json does not exist in the config directory, default config files will be used, as previously defined.
- Added additional tests in to test/unit/test_solver_config.cpp.
- **Note**: for now am assuming the camp-list has only two entries and is ordered as a species file followed by a mechanism/reactions file.
- To relax this assumption we could open each file in the CAMP list and search for JSON keys that determine the type of config file.  But based on previous discussions we will likely define a **new task** to re-organize the JSON parser, simply merging all config files in the CAMP list and simultaneously parsing species and reactions.

2023-09-26 15:08 UTC, K20shores requested changes

2023-09-26 15:08 UTC, K20shores commented on include/micm/configure/solver_config.hpp
> +        std::cout << "Reading CAMP config " << camp_config << std::endl;
Please remove or comment this out. Hopefully we will be adding a logger when we do #127, but for now I'd prefer we keep output relatively clear.

2023-09-26 15:08 UTC, K20shores commented on include/micm/configure/solver_config.hpp
> +          std::cout << element.get<std::string>() << std::endl;
same as above

2023-09-26 16:14 UTC, boulderdaze approved these changes

2023-09-26 17:14 UTC, mattldawson approved these changes
looks great! just two very minor comments

2023-09-26 17:14 UTC, mattldawson commented on include/micm/configure/solver_config.hpp
> +        // std::cout << "Reading CAMP config " << camp_config << std::endl;
can remove commented-out line

2023-09-26 17:14 UTC, mattldawson commented on include/micm/configure/solver_config.hpp
> +          // std::cout << element.get<std::string>() << std::endl;
can remove commented-out line

2023-09-27 16:58 UTC, K20shores approved these changes

2023-09-27 17:04 UTC, merged