Remove for each
NCAR/micm pull request #461
Opened 2024-04-17 14:08 UTC by K20shores

This is just to test the time difference between for each and a regular for loop

2024-04-19 15:30 UTC, K20shores commented on include/micm/solver/rosenbrock.inl
> +          errors_over_scale = errors_iter[idx] / (parameters_.absolute_tolerance_[idx % n_species] +
```suggestion
          errors_over_scale = errors_iter[idx] / (parameters_.absolute_tolerance_[y % n_species] +
```

should it actually be this?

2024-04-19 16:20 UTC, sjsprecious commented on include/micm/solver/rosenbrock.inl
> +          size_t idx = y * L + x;
Never mind. I am wrong and the current implementation is correct.

2024-04-19 18:33 UTC, sjsprecious approved these changes
@K20shores Nice work and thanks for addressing this issue!

2024-04-22 16:17 UTC, boulderdaze requested changes
Looks good!

2024-04-22 20:32 UTC, boulderdaze approved these changes
Thanks!

2024-04-22 21:42 UTC, mattldawson approved these changes
looks great!

2024-04-22 21:48 UTC, merged